on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build
    - name: deploy to gh-pages
      run: gh-pages -d public -r https://$GH_PAT@github.com/astralfrontier/flip-a-card.git
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
