on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build-csv
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@master
      with:
        root_file: template/cards.tex
        args: -xelatex -file-line-error -interaction=nonstopmode
    - run: cp cards.pdf static/
    - run: npm run build -- --prefix-paths
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
